In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
# Load your dataset
df = pd.read_csv("/content/drive/MyDrive/ LLM application for Maintenance Decision Making/Data/updated_dataset_correct_variable_names.csv")

In [ ]:
# Sample 500 random rows (set random_state for reproducibility)
sample_df = df.sample(n=500, random_state=42).reset_index(drop=True)
print(f"Sampled {len(sample_df)} rows")

Sampled 500 rows

In [ ]:
sample_df.shape

(500, 21)

In [ ]:
sample_df.columns

Index(['AADT', 'AADT Single Unit', 'AADT Combination', 'Future AADT',
       'International Roughness Index', 'Thickness of Rigid Pavements',
       'Thickness of Flexible Pavements', 'Thickness of Base Pavements',
       'Functional System', 'Urban Type', 'Surface Type', 'Base Type',
       'Rutting', 'Cracking Percent', 'Faulting', 'Relative Humidity',
       'Freezing Index', 'Average Temperature', 'Precipitation', 'Age',
       'Maintenance Intervention'],
      dtype='object')

In [ ]:
sample_df.dtypes

AADT                               float64
AADT Single Unit                   float64
AADT Combination                   float64
Future AADT                        float64
International Roughness Index      float64
Thickness of Rigid Pavements       float64
Thickness of Flexible Pavements    float64
Thickness of Base Pavements        float64
Functional System                   object
Urban Type                          object
Surface Type                        object
Base Type                           object
Rutting                            float64
Cracking Percent                   float64
Faulting                           float64
Relative Humidity                  float64
Freezing Index                     float64
Average Temperature                float64
Precipitation                      float64
Age                                  int64
Maintenance Intervention            object
dtype: object

In [ ]:
sample_df.head(10)

,AADT,AADT Single Unit,AADT Combination,Future AADT,International Roughness Index,Thickness of Rigid Pavements,Thickness of Flexible Pavements,Thickness of Base Pavements,Functional System,Urban Type,...,Base Type,Rutting,Cracking Percent,Faulting,Relative Humidity,Freezing Index,Average Temperature,Precipitation,Age,Maintenance Intervention
0,71446.0,4259.0,7445.0,85878.0,71.5,0.0,10.5,15.0,Interstate,rural,...,Asphalt or cement stabilized,0.2,0.0,0.0,75.5,224.4,11.6,1318.4,58,Thin Overlay
1,8300.0,130.0,40.0,10300.0,108.0,0.0,12.0,17.0,Minor Arterial,urban,...,Hot mix AC (Bituminous),0.1,2.0,0.0,78.2,216.0,10.4,1435.3,26,No Maintenance
2,750.0,43.0,7.0,1000.0,242.5,0.0,3.0,12.0,Major Collector,urban,...,Aggregate,0.1,0.0,0.0,77.6,254.6,10.4,1398.8,9,Thin Overlay
3,4513.0,50.0,14.0,5032.0,236.0,0.0,10.0,6.0,Major Collector,urban,...,Asphalt or cement stabilized,0.2,5.5,0.0,75.3,227.2,12.2,1246.0,67,No Maintenance
4,8875.0,502.0,28.0,13188.0,116.3,0.0,6.5,12.0,Minor Arterial,urban,...,Aggregate,0.1,0.3,0.0,84.0,25.0,9.4,1628.8,43,Thin Overlay
5,3917.0,71.0,55.0,5480.0,178.0,0.0,3.0,8.0,Principal Arterial – Other,urban,...,Asphalt or cement stabilized,0.0,0.0,0.0,51.2,24.2,16.4,454.6,73,Thin Overlay
6,1256.0,57.0,253.0,1758.0,60.0,0.0,4.2,12.0,Minor Arterial,urban,...,Aggregate,0.2,0.0,0.0,59.1,62.4,12.3,438.0,9,No Maintenance
7,47262.0,792.0,2978.0,51875.0,55.0,10.0,4.0,16.0,Interstate,urban,...,Hot mix AC (Bituminous),0.1,0.0,0.0,76.3,330.1,10.3,1280.2,55,No Maintenance
8,54944.0,3943.0,6443.0,72955.0,53.8,10.0,4.5,16.0,Interstate,urban,...,Asphalt or cement stabilized,0.2,0.0,0.0,75.9,251.0,11.1,1287.3,66,No Maintenance
9,24000.0,1090.0,1920.0,43000.0,55.8,0.0,11.5,8.0,Principal Arterial – Other Freeways and Expres...,urban,...,Aggregate,0.2,34.0,0.0,77.2,35.2,15.4,1361.1,28,No Maintenance

In [ ]:
sample_df['Maintenance Intervention'].value_counts()

Maintenance Intervention
No Maintenance    255
Thin Overlay      178
Thick Overlay      53
Resurfacing        14
Name: count, dtype: int64

In [ ]:
##### sample_df.to_csv('/content/drive/MyDrive/ LLM application for Maintenance Decision Making/Data/sample_df_500.csv', index=False)